# Generated by Django 5.1.2 on 2024-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.CharField(choices=[('free', 'Free'), ('linear', 'Linear')], default='free', max_length=10),
        ),
    ]
