# Generated by Django 5.1.2 on 2024-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_alter_formposition_process_alter_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
