# Generated by Django 5.1.2 on 2024-10-28 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0004_alter_question_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseFormHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_response_histories', to='dynamic_forms.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
