# Generated by Django 5.1.2 on 2024-10-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_watchprocesshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='password',
        ),
    ]
